#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run prod

echo "Arquivos zipados em /dist"

exec 1>&2
exec < /dev/tty

# Prompt 'Fazer upload'?
read -p "Quer fazer upload da versão? (y/n)" uploadAnswer

if [ $uploadAnswer = 'y' ]; then
    # Em qual site?
    read -p "Realizar upload em qual URL?" uploadURL

    # Com qual Chave p/ API Admin?
    read -p "Qual sua chave para a API de Admin?" uploadAPIKey

    # Fazer o curl
    curl -X POST -F 'file=@./dist/ligenews-v0.0.1.zip' -H "Authorization: Ghost $uploadAPIKey" -H "Accept-Version: 5.0" http://{$uploadURL}/ghost/api/admin/themes/upload
    
    echo "CURL finalizado..."

elif [ $uploadAnswer = 'n' ]; then
    echo "Upload não realizado..."
fi

# Apagar os dados do console...