#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run prod
echo "Arquivos zipados em /dist"

# Prompt 'Fazer upload'?
echo "Quer fazer upload da versão?"
read uploadPrompt

# Em qual site?

# Com qual Chave p/ API Admin?

# Fazer o curl

# Apagar os dados do console...